ALTER TYPE "DiscoveryAnswerType" ADD VALUE IF NOT EXISTS 'CURRENCY_RANGE';
ALTER TYPE "DiscoveryAnswerType" ADD VALUE IF NOT EXISTS 'DOMAIN';
ALTER TYPE "DiscoveryAnswerType" ADD VALUE IF NOT EXISTS 'SLIDER';
